### ISSUE TITLE
Preprocessing fix

### ISSUE THREAD

**Issue by blahami2** [cc-routing/routing-sara#49]
Preprocessing throws Nullpointer for cell ratio / core ratio >= 0.5

**Comment by blahami2** [comment]
```
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.2, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.1, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Exception in thread "main" java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:78)
	at cz.blahami2.routingsaratester.Main.run(Main.java:210)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1


"C:\Program Files\Java\jdk1.8.0_102\bin\java" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_102\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\rt.jar;C:\Users\blaha\Documents\IntelliJProjects\routing-tester\target\classes;C:\Users\blaha\.m2\repository\cz\certicon\Routing\routing-sara\1.0-SNAPSHOT\routing-sara-1.0-SNAPSHOT.jar;C:\Users\blaha\.m2\repository\org\jgrapht\jgrapht-core\0.9.2\jgrapht-core-0.9.2.jar;C:\Users\blaha\.m2\repository\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\blaha\.m2\repository\org\jdesktop\swingx\jxmapviewer2\1.3.1\jxmapviewer2-1.3.1.jar;C:\Users\blaha\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\blaha\.m2\repository\org\xerial\sqlite-jdbc\3.8.11.2\sqlite-jdbc-3.8.11.2.jar;C:\Users\blaha\.m2\repository\org\graphstream\gs-core\1.3\gs-core-1.3.jar;C:\Users\blaha\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\blaha\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\blaha\.m2\repository\org\graphstream\pherd\1.0\pherd-1.0.jar;C:\Users\blaha\.m2\repository\org\graphstream\mbox2\1.0\mbox2-1.0.jar;C:\Users\blaha\.m2\repository\org\graphstream\gs-ui\1.3\gs-ui-1.3.jar;C:\Users\blaha\.m2\repository\org\graphstream\gs-algo\1.3\gs-algo-1.3.jar;C:\Users\blaha\.m2\repository\org\apache\commons\commons-math\2.1\commons-math-2.1.jar;C:\Users\blaha\.m2\repository\org\apache\commons\commons-math3\3.4.1\commons-math3-3.4.1.jar;C:\Users\blaha\.m2\repository\org\jfree\jfreechart\1.0.14\jfreechart-1.0.14.jar;C:\Users\blaha\.m2\repository\org\jfree\jcommon\1.0.17\jcommon-1.0.17.jar;C:\Users\blaha\.m2\repository\xml-apis\xml-apis\1.3.04\xml-apis-1.3.04.jar;C:\Users\blaha\.m2\repository\com\lowagie\itext\2.1.5\itext-2.1.5.jar;C:\Users\blaha\.m2\repository\bouncycastle\bcmail-jdk14\138\bcmail-jdk14-138.jar;C:\Users\blaha\.m2\repository\bouncycastle\bcprov-jdk14\138\bcprov-jdk14-138.jar;C:\Users\blaha\.m2\repository\org\scala-lang\scala-library\2.10.1\scala-library-2.10.1.jar;C:\Users\blaha\.m2\repository\net\sourceforge\streamsupport\streamsupport\1.5.1\streamsupport-1.5.1.jar;C:\Users\blaha\.m2\repository\de\erichseifert\gral\gral-core\0.11\gral-core-0.11.jar;C:\Users\blaha\.m2\repository\de\erichseifert\vectorgraphics2d\VectorGraphics2D\0.10\VectorGraphics2D-0.10.jar;C:\Users\blaha\.m2\repository\cz\blahami2\utils\table\1.0-SNAPSHOT\table-1.0-SNAPSHOT.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain cz.blahami2.routingsaratester.Main
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.2, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.1, coreRatio=0.2, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.9, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK

```

**Comment by blahami2** [comment]
```
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Exception in thread "main" java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:79)
	at cz.blahami2.routingsaratester.Main.run(Main.java:211)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by blahami2** [comment]
```
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.1, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.5, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.5, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:80)
	at cz.blahami2.routingsaratester.Main.run(Main.java:211)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.5, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:80)
	at cz.blahami2.routingsaratester.Main.run(Main.java:211)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:80)
	at cz.blahami2.routingsaratester.Main.run(Main.java:211)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[10, 100, 1000], cellRatio=0.9, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
	at cz.certicon.routing.model.graph.preprocessing.ContractNode.mergeWith(ContractNode.java:58)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.contractNode(NaturalCutsFilter.java:257)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.minimalCut(NaturalCutsFilter.java:312)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.getCutEdges(NaturalCutsFilter.java:219)
	at cz.certicon.routing.algorithm.sara.preprocessing.filtering.NaturalCutsFilter.filter(NaturalCutsFilter.java:101)
	at cz.certicon.routing.algorithm.sara.preprocessing.BottomUpPreprocessor.preprocess(BottomUpPreprocessor.java:56)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.run(TestRunner.java:82)
	at cz.blahami2.routingsaratester.testrunner.logic.TestRunner.runForResult(TestRunner.java:209)
	at cz.blahami2.routingsaratester.parametertuning.ParameterTuningController.run(ParameterTuningController.java:80)
	at cz.blahami2.routingsaratester.Main.run(Main.java:211)
	at cz.blahami2.routingsaratester.Main.main(Main.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.1, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.1, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.5, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.5, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.5, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.9, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.9, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[40, 1600, 64000], cellRatio=0.9, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.1, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.1, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.1, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.5, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.5, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
Input has failed.
java.lang.NullPointerException
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.5, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
Input has failed.
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.9, coreRatio=0.1, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.9, coreRatio=0.5, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
OK
Preprocessing... input = PreprocessingInput(cellSizes=[160, 25600, 4096000], cellRatio=0.9, coreRatio=0.9, lowIntervalProbability=0.03, lowIntervalLimit=0.6, numberOfAssemblyRuns=10, numberOfLayers=3)
java.lang.NullPointerException
Input has failed.
```

**Comment by blahami2** [comment]
Fixed (NaturalCutsFilter:239 nullcheck - find out why there are nulls in the first place)
